name: clean_architecture_template
description: A Flutter project template based on clean architecture.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  #view
  mask_text_input_formatter: ^2.4.0
  url_launcher: ^6.1.7
  badges: ^3.0.2
  flutter_app_badger: ^1.5.0
  flutter_svg: ^2.0.5
  bot_toast: ^4.0.3


  #logic
  get_it: ^7.2.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  rxdart: ^0.27.5
  flutter_keyboard_visibility: ^5.4.0


  #rest
  dio: ^5.1.1
  http_parser: ^4.0.2


  #storage
  shared_preferences: ^2.0.15


  #config
  easy_localization: ^3.0.1
  easy_localization_loader: ^1.0.1+1
  responsive_sizer: ^3.1.1
  flutter_native_splash: ^2.2.13
  enum_to_string: ^2.0.1
  fimber: ^0.6.6
  pretty_dio_logger: ^1.1.1
  build_runner: ^2.3.2
  flutter_native_timezone: ^2.0.0
  internet_connection_checker: ^1.0.0+1
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/icons/png/
    - assets/translations/
    - fonts/

  #fonts:
   # - family: Montserrat
   #   fonts:
   #     - asset: fonts/Montserrat-Regular.ttf
   #       weight: 400
   #     - asset: fonts/Montserrat-Medium.ttf
   #       weight: 500
   #     - asset: fonts/Montserrat-Bold.ttf
   #       weight: 700
   #     - asset: fonts/Montserrat-Black.ttf
   #       weight: 900
